name: 'modern_data_stack_dbt'
version: '1.0.0'
config-version: 2

profile: 'modern_data_stack_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  modern_data_stack_dbt:
    examples:
      +materialized: view